---
title: "Chapter 3 Testing"
output: html_document
---

```{r}
library(tigris)
library(tidyverse)
library(censusapi)
library(sf)
library(leaflet)
library(mapboxapi)
library(jsonlite)

acs_vars_2019_5yr <-
  listCensusMetadata(
    name = "2019/acs/acs5",
    type = "variables"
  )

sept21_patterns <- read_csv("neighborhood_patterns.csv.gz") # adjust your filepath as necessary
```

```{r}
ca_cbgs <- block_groups("CA", cb = T, progress_bar = F)

stanford_boundary <- places("CA", cb = T, progress_bar = F) %>% 
  filter(NAME == "Stanford")

stanford_cbgs <- 
  ca_cbgs %>% 
  st_centroid() %>% 
  .[stanford_boundary, ] %>% 
  st_drop_geometry() %>% 
  left_join(ca_cbgs %>% select(GEOID)) %>% 
  st_as_sf()
```

```{r}
leaflet() %>% 
  addMapboxTiles(
    style_id = "streets-v11",
    username = "mapbox"
  ) %>% 
  addPolygons(
    data = stanford_cbgs,
    fill = F
  )
```

```{r}
stanford_patterns <-
  sept21_patterns %>% 
  filter(area %in% stanford_cbgs$GEOID)

rm(sept21_patterns)
```

```{r}
json <-
  stanford_patterns$device_home_areas[1] %>% 
  fromJSON() %>%
  unlist() %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  rename(
    origin_cbg = "rowname",
    device_count = "."
  )

head(json)
```

```{r}
origin_cbgs <-
  1:nrow(stanford_patterns) %>% 
  map_dfr(function(row){
    
    json <-
      stanford_patterns$device_home_areas[row] %>% 
      fromJSON() %>%
      unlist() %>% 
      as.data.frame() %>% 
      rownames_to_column() %>% 
      rename(
        origin_cbg = "rowname",
        device_count = "."
      ) %>% 
      mutate(
        device_count = ifelse(
          device_count == 4,
          3,
          device_count
        )
      )
    
  })
```

```{r}
origin_cbgs_merged <-
  origin_cbgs %>% 
  group_by(origin_cbg) %>% 
  summarize(
    device_count = max(device_count)
  )
```

```{r}
home_panel_summary <- read_csv("home_panel_summary.csv") # adjust your filepath as necessary
```

```{r}
Sys.setenv(CENSUS_KEY="0f0e2bffc9d96d5405bcb932e25318a4edb32602")

ca_cbgs_pop <-
  counties("CA", cb = T, progress_bar = F) %>%
  pull(COUNTYFP) %>% 
  map_dfr(function(x){
    getCensus(
      name = "acs/acs5",
      vintage = 2019,
      region = "block group:*",
      regionin = paste0("state:06+county:", x),
      vars = "B01001_001E"
    )
  }) %>% 
  transmute(
    census_block_group =
      paste0(state,county,tract,block_group),
    pop = B01001_001E
  )
```

```{r}
origin_cbgs_pop <-
  origin_cbgs_merged %>% 
  left_join(
    ca_cbgs_pop,
    by = c("origin_cbg" = "census_block_group")
  )

sum(is.na(origin_cbgs_pop$pop)) # all those are outside of CA
```

```{r}
origin_cbgs_normalized <-
  origin_cbgs_pop %>% 
  filter(!is.na(pop)) %>% 
  left_join(
    home_panel_summary %>% 
      select(origin_cbg = census_block_group, number_devices_residing)
  ) %>% 
  mutate(
    visits = (device_count * pop / number_devices_residing) %>% round()
  ) %>% 
  left_join(ca_cbgs %>% select(origin_cbg = GEOID)) %>% 
  st_as_sf()
```

```{r}
visits_pal <- colorNumeric(
  palette = "Reds",
  domain = origin_cbgs_normalized %>% 
    arrange(desc(visits)) %>% 
    pull(visits) %>% 
    .[-c(1:6)]
)

leaflet() %>% 
  addMapboxTiles(
    style_id = "light-v9",
    username = "mapbox"
  ) %>% 
  addPolygons(
    data = stanford_cbgs,
    fill = F
  ) %>% 
  addPolygons(
    data = origin_cbgs_normalized,
    fillColor = ~visits_pal(visits),
    color = "red",
    weight = 1,
    fillOpacity = 0.75,
    label = ~visits
  ) %>% 
  addLegend(
    data = origin_cbgs_normalized,
    pal = visits_pal,
    values = origin_cbgs_normalized %>% 
      arrange(desc(visits)) %>% 
      pull(visits) %>% 
      .[-c(1:6)],
    title = "Visits to<br>Stanford in<br>Sept 2021"
  )
```

```{r}
stanford_origin <-
  origin_cbgs_normalized %>% 
  st_centroid() %>% 
  st_coordinates()

stanford_destination <-
  stanford_boundary %>% 
  st_centroid() %>% 
  st_coordinates()

stanford_route <- 
  1:nrow(stanford_origin) %>%
  map_dfr(function(x){
    mb_directions(
      origin = stanford_origin[x, ],
      destination = stanford_destination,
      profile = "driving-traffic"
    )
  }) %>% 
  st_as_sf()
```

```{r}
leaflet() %>%
  addMapboxTiles(
    style_id = "light-v9",
    username = "mapbox"
  ) %>%
  addPolylines(
    data = stanford_route
  )
```

```{r}
travel_time_mode <-
  counties("CA", cb = T, progress_bar = F) %>%
  pull(COUNTYFP) %>% 
  map_dfr(function(x){
    getCensus(
      name = "acs/acs5",
      vintage = 2019,
      region = "block group:*",
      regionin = paste0("state:06+county:", x),
      vars = "group(B08134)"
    )
  }) %>% 
  mutate(
    cbg =
      paste0(state,county,tract,block_group)
  ) %>%
  filter(cbg %in% origin_cbgs_normalized$origin_cbg) %>% 
  select(!c(GEO_ID,state,county,tract,block_group,NAME) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "variable",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_5yr %>% 
      select(name, label), 
    by = c("variable" = "name")
  ) %>% 
  select(-variable) %>% 
  separate(
    label,
    into = c(NA, NA, "total", "mode", "carpool", "time"),
    sep = "!!"
  ) %>% 
  mutate(
    mode = case_when(
      total %in% c(
        "Less than 10 minutes",
        "10 to 14 minutes",
        "15 to 19 minutes",
        "20 to 24 minutes",
        "25 to 29 minutes",
        "30 to 34 minutes",
        "35 to 44 minutes",
        "45 to 59 minutes",
        "60 or more minutes"
      ) ~ "Total",
      mode == "Drove alone:" ~ mode,
      carpool %in% c(
        "In 2-person carpool:",
        "In 3-or-more-person carpool:"
      ) ~ carpool
    ),
    time = case_when(
      mode == "Total" ~ total,
      mode == "Drove alone:" ~ carpool,
      mode == carpool ~ time
    )
  ) %>% 
  filter(!is.na(time)) %>% 
  select(-total, -carpool) %>% 
  pivot_wider(
    names_from = mode,
    values_from = estimate
  ) %>% 
  mutate(
    perc_veh1 = `Drove alone:`/Total,
    perc_veh2 = `In 2-person carpool:`/Total,
    perc_veh3 = `In 3-or-more-person carpool:`/Total
  )
```

```{r}
stanford_trips <-
  origin_cbgs_normalized %>% 
  cbind(
    stanford_route %>% 
      st_drop_geometry()
  ) %>% 
  mutate(
    time = case_when(
      duration < 10 ~ "Less than 10 minutes",
      duration < 15 ~ "10 to 14 minutes",
      duration < 20 ~ "15 to 19 minutes",
      duration < 25 ~ "20 to 24 minutes",
      duration < 30 ~ "25 to 29 minutes",
      duration < 35 ~ "30 to 34 minutes",
      duration < 45 ~ "35 to 44 minutes",
      duration < 60 ~ "45 to 59 minutes",
      TRUE ~ "60 or more minutes"
    )
  ) %>% 
  left_join(
    travel_time_mode %>% 
      select(
        origin_cbg = cbg,
        time,
        perc_veh1,
        perc_veh2,
        perc_veh3
      ),
    by = c("origin_cbg", "time")
  ) %>% 
  mutate(
    vehicles = 
      visits * perc_veh1 + 
      visits * perc_veh2 / 2 +
      visits * perc_veh3 / 3,
    vmt = vehicles * distance * 2
  )
```

```{r}
recorded_visits <- sum(stanford_trips$device_count)/
  sum(stanford_patterns$raw_device_counts)

recorded_visits
```
```{r}
sum(stanford_trips$vmt, na.rm = T)/recorded_visits
```

```{r}
emfac <- 
  read_csv("EMFAC2021-EI-202xClass-BayAreaAQMD-2022-Summer-20220203075721.csv", skip = 8) %>% 
  transmute(
    Category = `Vehicle Category`,
    Fuel_Type = Fuel,
    Percent_Trips = Trips/sum(Trips),
    Percent_Miles = `Total VMT`/sum(`Total VMT`),
    `MTCO2_Running_Exhaust` = CO2_RUNEX/`Total VMT`,
    `MTCO2_Start_Exhaust` = CO2_STREX/Trips
  )

emfac
```
```{r}
stanford_trips_ghg <-
  emfac %>% 
  mutate(
    trips = Percent_Trips * sum(stanford_trips$visits, na.rm = T),
    vmt = Percent_Miles * sum(stanford_trips$vmt, na.rm = T),
    ghg = vmt*MTCO2_Running_Exhaust + trips*MTCO2_Start_Exhaust*2
  )
```

```{r}
sum(stanford_trips_ghg$ghg)/recorded_visits
```

