---
title: "Week3ThursdayLab"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
path <- "/Volumes/GoogleDrive/Shared drives/SFBI/Data Library/NHTS/nhts17-caltrans-tsdc-download/"

pois <- st_read("/Volumes/GoogleDrive/Shared drives/SFBI/Data Library/OSM/gis_osm_pois_a_free_1.shp")

library(tidyverse)
library(readxl)
library(tigris)
library(sf)
library(leaflet)
```

```{r}
survey_household <- read_csv(paste0(path,"survey_household.csv"))

survey_person <- read.csv(paste0(path,"survey_person.csv")) # read_csv() appeared to trigger an error because of a formatting issue, so my second attempt is always the base R version of this function, read.csv(). It generally gives the same result.

survey_trip <- read_csv(paste0(path,"survey_trip.csv"))

survey_person_weights_7day <- read_csv(paste0(path,"survey_person_weights_7day.csv"))

nhts_lookup <- read_excel(
  paste0(path,"data_elements.xlsx"), 
  sheet = "Value Lookup"
)
```
# FOR ASSN

```{r}
path <- "/Volumes/GoogleDrive/Shared drives/SFBI/Data Library/NHTS/nhts17-caltrans-tsdc-download/"

pois <- st_read("/Volumes/GoogleDrive/Shared drives/SFBI/Data Library/OSM/gis_osm_pois_a_free_1.shp")

library(tidyverse)
library(readxl)
library(tigris)
library(sf)
library(leaflet)
```

```{r}
pois_summary <- pois %>% 
  st_drop_geometry() %>% 
  group_by(fclass) %>% 
  count() %>% 
  arrange(desc(n))

smc_boundary <- counties("CA") %>% 
  filter(NAME == "San Mateo") %>% 
  st_transform(st_crs(pois))

smc_pois <- pois %>% 
  .[smc_boundary, ] %>% 
  rename(amenity = fclass)

mapview(smc_pois, zcol = "amenity")

#Let's not use all POIs lets filter down to differentiate

smc_pois_filter <- smc_pois %>% 
  filter(amenity %in% c(
    "park",
    "convenience",
    "restaurant",
    "supermarket",
    "library"
  ))

mapview(smc_pois_filter, zcol = "amenity")

```

## can save filtered as RDS here if you want.

```{r}
smc_cbgs <- block_groups("CA","San Mateo")

nfo_boundary <- places("CA") %>% 
  filter(NAME == "North Fair Oaks")

nfo_cbgs <- smc_cbgs %>% 
  st_centroid() %>% 
  .[nfo_boundary, ] %>% 
  st_drop_geometry() %>% 
  left_join(smc_cbgs %>% select(GEOID)) %>% 
  st_as_sf()

mapview(nfo_cbgs)
```

```{r}
# Need mapbox token here first

isochrone <- mb_isochrone(
  nfo_cbgs,
  profile = "walking",
  time = c(5,10,15)
)

isochrone[1:3,] %>% mapview()

saveRDS(isochrone,"somewhere.RDS") # SAVE HERE TO SAVE CREDITS
```

```{r}
access_raw <- isochrone %>% 
  st_make_valid() %>% 
  st_join(smc_pois_filter) %>% 
  st_drop_geometry() %>% 
  filter(!is.na(osm_id))
```

