---
title: "AlessandroKerr_A2"
output: html_document
author: "Alessandro Kerr"
date: " Oct 5, 2021"

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
knitr::opts_chunk$set(warning = F, message = F)
```

```{r}
library(tidyverse)
library(plotly)
library(sf)
library(tigris)
library(leaflet)
library(censusapi)
library(mapview)
library(units)

```

```{r}
# IMPORT CENSUS DATA AND VARIABLES FOR 2020

Sys.setenv(CENSUS_KEY="0f0e2bffc9d96d5405bcb932e25318a4edb32602")

smc_pop_2020 <-
  getCensus(
    name = "dec/pl",
    vintage = 2020,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = "P1_001N"
  ) %>% 
  transmute(
    block =
      paste0(state,county,tract,block),
    pop = P1_001N
  )

dec_vars_2020 <-
  listCensusMetadata(
    name = "2020/dec/pl",
    type = "variables"
  )


```


```{r}
#IMPORT SMC BLOCKS AND SAN CARLOS BOUNDARIES

smc_blocks_2020 <- blocks("CA", "San Mateo", year = 2020, progress_bar = F)

nfo_boundary <- places("CA", progress_bar = "F") %>%
  filter(NAME == "North Fair Oaks")

#FILTER SMC CENSUS DATA FOR 2020 TO ONLY SAN CARLOS

nfo_blocks_2020 <- smc_pop_2020 %>% 
  left_join(smc_blocks_2020 %>% select(block = GEOID20)) %>% 
  st_as_sf() %>% 
  st_centroid() %>% 
  .[nfo_boundary, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(smc_blocks_2020 %>% select(block = GEOID20)) %>% 
  st_as_sf()

#mapview(nfo_blocks_2020, zcol = "pop")

```

```{r}
# IMPORT CENSUS DATA AND VARIABLES FOR 2020

Sys.setenv(CENSUS_KEY="0f0e2bffc9d96d5405bcb932e25318a4edb32602")

smc_pop_2010 <-
  getCensus(
    name = "dec/pl",
    vintage = 2010,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = "P001001"
  ) %>% 
  transmute(
    block =
      paste0(state,county,tract,block),
    pop = P001001
  )

dec_vars_2010 <-
  listCensusMetadata(
    name = "2010/dec/pl",
    type = "variables"
  )

```

```{r}
#FILTER 2010 CENSUS DATA TO ONLY SAME AS 2020 BLOCKS

smc_blocks_2010 <- blocks("CA", "San Mateo", year = 2010, progress_bar = F)

nfo_blocks_2010 <- smc_pop_2010 %>% 
  left_join(smc_blocks_2010 %>% select(block = GEOID10)) %>% 
  st_as_sf() %>% 
  st_centroid() %>% 
  .[nfo_boundary, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(smc_blocks_2010 %>% select(block = GEOID10)) %>% 
  st_as_sf()


# sc_blocks_2010 <- smc_pop_2010 %>% 
#   left_join(smc_blocks_2020 %>% select(block = GEOID20)) %>% 
#   st_as_sf() %>% 
#   st_centroid() %>% 
#   .[sc_blocks_2020, ] %>% 
#   st_set_geometry(NULL) %>% 
#   left_join(smc_blocks_2020 %>% select(block = GEOID20)) %>% 
#   st_as_sf()

#mapview(nfo_blocks_2010, zcol = "pop")
#mapview(nfo_blocks_2010) + mapview(nfo_blocks_2020)

# leaflet() %>% 
#   addProviderTiles(providers$CartoDB.Positron) %>% 
#   addPolygons(
#     data = sc_blocks_2020,
#     stroke = F,
#     fillOpacity = 0.5
#   ) %>% 
#   addPolygons(
#     data = sc_blocks_2010,
#     color = "red",
#     weight = 0.75,
#     fill = F
#   )
```

```{r}
#COOKIE CUTTER TO COMBINE GEOMETRY OF THE BLOCKS

nfo_comb_blocks <- smc_blocks_2010[nfo_blocks_2020, ]

nfo_blocks_area <- 
  nfo_comb_blocks %>%
  st_transform(26910) %>% 
  mutate(area = st_area(.))

nfo_blocks_int <- 
  nfo_blocks_area %>%
  st_intersection(
    nfo_blocks_2010 %>% 
        st_transform(26910)
  )
```

```{r}
#DISTRIBUTE POPULATION
nfo_blocks_3 <-
  nfo_blocks_2020 %>% 
  st_transform(26910) %>% 
  mutate(original_area = st_area(.)) %>% 
  st_intersection(
    nfo_blocks_2010 %>% 
      st_transform(26910)
  ) %>% 
  mutate(
    leftover_area = st_area(.),
    perc_area = leftover_area / original_area,
    pop = pop * perc_area
  )



#sum(nfo_blocks_3$pop.1*nfo_blocks_3$perc_area)
  

```

```{r}
#CLEANING UP NFO_BLOCKS_3 DATA
nfo_clean <- nfo_blocks_3 %>%
  group_by(block) %>% 
  summarise(
    pop2020 = sum(pop*perc_area),
    pop2010 = sum(pop.1*perc_area))

```


```{r}
#CALCULATING DENSITY CHANGE

nfo_plot <- nfo_clean %>%
  st_transform(26910) %>% 
  mutate(area = st_area(.)) %>%
  mutate(area = area*0.000247105) %>%
  mutate(density = pop2020 - pop2010) %>%
  mutate(density = density/area) %>%
  drop_units %>%
  filter(density>=-50) %>%
  st_set_geometry(NULL) %>% 
  left_join(smc_blocks_2020 %>% select(block = GEOID20)) %>% 
  st_as_sf()
  
```


```{r}
#FILTERING 2020 DATA TO ONLY INCLUDE CENTROIDS THAT EXIST IN 2010 (FILTER DOWN)
# sc_joined <- sc_blocks_2020 %>%
#   st_centroid() %>% 
#   .[sc_blocks_2010, ] %>%
#   st_set_geometry(NULL) %>% 
#   left_join(sc_blocks_2020 %>% select(block)) %>% 
#   st_as_sf() %>%
#   cbind(sc_blocks_2010$pop) %>%
#   mutate(area = st_area(.)) 

# sc_joined2 <- sc_joined %>%
#   st_set_geometry(NULL) %>%
#   right_join(sc_blocks_2010)%>%
#   st_as_sf() 






```

```{r}
#PLOTTING

dpal <- colorNumeric(palette = "Reds", domain = nfo_plot$density)

leaflet() %>%
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons( 
    data = nfo_plot,
    fillColor = ~dpal(density),
    color = "white",
    opacity = 0.5,
    fillOpacity = 0.75,
    weight = 1,
    label = ~paste0(
      round(density), 
      " Person Per Acre Change Between 2010 and 2020 "
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    ) 
  ) %>% 
  addLegend(
    data = nfo_plot,
    pal = dpal,
    values = ~density,
    title = "Change in Density <br> in North Fair Oaks <br> (People per Acre) <br> Between 2010 and 2020"
  )
  
```



```{r}
# #CALC CHANGE IN DENSITY
# 
# 
# sc_density <- sc_joined %>%
#   mutate(sc_blocks_2010 %>%
#            )
```


```{r}
# #JOIN 2010 and 2020 data w/ different boundaries for each tract
# smc_join_blocks <- 
#   smc_blocks_2020 %>%
#   select(block = GEOID20) %>%
#   left_join(smc_pop_2020) %>%
#   st_transform(26910) %>% 
#   mutate(original_area = st_area(.)) %>% 
#   st_intersection(
#     sc_blocks_2010 %>% 
#       st_transform(26910)
#   ) %>% 
#   mutate(
#     leftover_area = st_area(.),
#     perc_area = leftover_area / original_area,
#     pop = pop * perc_area
#   )

```




```{r}
# #smc_pop_race_2020 <-
#   getCensus(
#     name = "dec/pl",
#     vintage = 2020,
#     region = "block:*", 
#     regionin = "state:06+county:081",
#     vars = "group(P1)"
#   ) %>% 
#   mutate(
#     block =
#       paste0(state,county,tract,block)
#   ) %>% 
#   select(!c(GEO_ID,state,county,tract,NAME) & !ends_with(c("NA"))) %>% 
#   pivot_longer(
#     ends_with("N"),
#     names_to = "name",
#     values_to = "estimate"
#   ) %>%
#   left_join(
#     dec_vars_2020 %>% 
#       select(name, label)
#   ) %>% 
#   select(-name) %>% 
#   separate(
#     label,
#     into = c(NA,NA,"category1","category2"),
#     sep = "!!"
#   ) %>%
#   filter(!is.na(age))
# 
# #smc_pop_race_2020 <- smc_pop_race_2020 %>% 
#   mutate(
#     race = case_when(
#       category1 == "Population of two or more races:" & is.na(category2) ~ "Two or more races",
#       category1 == "Population of two or more races:" ~ "",
#       !is.na(category2) ~ category2,
#       TRUE ~ ""
#     )
#   )
# 
# #smc_pop_race_2020 <- smc_pop_race_2020 %>% 
#   filter(race != "") %>% 
#   select(block, race, pop = estimate)
# 
# #smc_pop_race_2010 <-
#   getCensus(
#     name = "dec/pl",
#     vintage = 2010,
#     region = "block:*", 
#     regionin = "state:06+county:081",
#     vars = "group(P1)"
#   ) %>% 
#   mutate(
#     block =
#       paste0(state,county,tract,block)
#   ) %>% 
#   select(!c(GEO_ID,state,county,tract,NAME)) %>% 
#   pivot_longer(
#     starts_with("P"),
#     names_to = "name",
#     values_to = "estimate"
#   ) %>%
#   left_join(
#     dec_vars_2010 %>% 
#       select(name, label)
#   ) %>% 
#   select(-name) %>% 
#   separate(
#     label,
#     into = c(NA,NA,"category1","category2"),
#     sep = "!!"
#   )
# ```
# 
# ```{r}
# smc_pop_race_2010 <- smc_pop_race_2010 %>% 
#   mutate(
#     race = case_when(
#       category1 == "Population of two or more races:" & is.na(category2) ~ "Two or more races",
#       category1 == "Population of two or more races:" ~ "",
#       !is.na(category2) ~ category2,
#       TRUE ~ ""
#     )
#   )
# 
# smc_pop_race_2010 <- smc_pop_race_2010 %>% 
#   filter(race != "") %>% 
#   select(block, race, pop = estimate)
```

```{r}
# mp_boundary <- places("CA", progress_bar = F) %>% 
#   filter(NAME == "Menlo Park")
# 
# mp_pop_2020 <- smc_pop_2020 %>% 
#   left_join(smc_blocks_2020 %>% select(block = GEOID20)) %>% 
#   st_as_sf() %>% 
#   st_centroid() %>% 
#   .[mp_boundary, ] %>% 
#   st_set_geometry(NULL) %>% 
#   left_join(smc_blocks_2020 %>% select(block = GEOID20)) %>% 
#   st_as_sf()
```

```{r}

```

```{r}
# mp_blocks_2020 <- smc_blocks_2020[smc_pdas, ]
# 
# mp_blocks_area <- 
#    %>% 
#   st_transform(26910) %>% 
#   mutate(area = st_area(.))
# 
# #smc_census_blocks <- smc_blocks_2020[mp_blocks_area, ]
# 
# smc_pop_race_2010_2 <-
#   getCensus(
#     name = "dec/pl",
#     vintage = 2010,
#     region = "block:*", 
#     regionin = "state:06+county:081",
#     vars = "group(P1)"
#   ) %>% 
#   mutate(
#     block =
#       paste0(state,county,tract,block)
#   ) %>% 
#   select(!c(state,county,tract,NAME)) %>% 
#   pivot_longer(
#     starts_with("P"),
#     names_to = "name",
#     values_to = "estimate"
#   ) %>%
#   left_join(
#     dec_vars_2010 %>% 
#       select(name, label)
#   ) %>% 
#   select(-name) %>% 
#   separate(
#     label,
#     into = c(NA,NA,"category1","category2"),
#     sep = "!!") %>%
#   select(-estimate, -category1,-category2)
# 
# 
# mp_pop_2010 <-
#   mp_blocks_area %>%
#   st_intersection(
#     smc_pop_race_2010_2 %>% 
#       st_transform(26910)
#   )
```

