---
title: "Final Project"
author: "Alessandro Kerr"
date: " Dec. X, 2021"
output: html_document
---

```{r setup, include=FALSE}


knitr::opts_chunk$set(echo = F)
knitr::opts_chunk$set(warning = F, message = F)

library(tidyverse)
library(plotly)
library(sf)
library(tigris)
library(leaflet)
library(censusapi)
library(lubridate)
library(dplyr)
library(mapview)
```

#FILTER DATA TO BAY AREA


```{r}
#tracts <- tracts("CA", county = c("001","013","041","055","075","081","085","095","097"),cb = T, progress_bar = F)

tracts <- tracts("CA", county = 081, cb = T, progress_bar = F)
```

```{r}
tracts_water <- tracts %>%
  filter(AWATER > 0)

mapview(tracts_water)

places <- places("CA", progress_bar = F)

mapview(places)


```

```{r}

library(devtools)
install_github('walkerke/tigris')
library(tigris)

smc_blocks_2020 <- blocks("CA", "San Mateo", year = 2019, progress_bar = F) %>%
  filter(AWATER10 > 0)

mapview(smc_blocks_2020)
```



```{r}
library(zipcode)
zipcodes <- search_county("San Mateo", "CA")
```
```{r}
mapview(zipcodes)

zipcodes_geo <- geocode_zip(zipcodes)
```

```{r}




```
```{r}
bay_zips_water <- bay_zips %>%
  filter(AWATER10 >0)

mapview(bay_zips)

```

```{r}
# library(dataRetrieval)
# vignette("dataRetrieval", package = "dataRetrieval")
# 
# #GET DAILY WATER DATA
# 
# siteNumbers <- c("11162630", "373025122065901")
# siteInfo <- readNWISsite(siteNumbers) #Gives Site Number Details
# 
# siteNumber1 <- "11162630" #Half Moon Bay Water Station
# parameterCd <- "00065"
# startDate <- "2021-01-01"
# endDate <- "2021-11-23"
# statCd <- "00001"
# 
# gage_height <- readNWISdv(siteNumber1,parameterCd,startDate,endDate,statCd)
```

```{r}
bay_analyze <- bay_filtered %>%
  st_centroid() %>%
  mutate(rw_dist = st_distance(geometry, rw_flood$geometry), 
        sf_dist = st_distance(geometry, sf_flood$geometry)) %>%
  mutate(station = ifelse(rw_dist>sf_dist, 1, 0)) %>%
  st_drop_geometry() %>% 
  left_join(bay_blocks %>% select(GEOID)) %>% 
  st_as_sf() %>% 
  mutate(water_height = ifelse(station ==1, sf_flood$water_height, rw_flood$water_height))


  bay_analyze$station = as.character(bay_analyze$station)
  


 mapview(bay_analyze, zcol = "station")
```

