---
title: "AlessandroKerr_A4"
output: html_document
author: "Alessandro Kerr"
date: " Oct 19, 2021"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
knitr::opts_chunk$set(warning = F, message = F)
```

```{r}
library(tidyverse)
library(plotly)
library(sf)
library(tigris)
library(leaflet)
library(censusapi)
library(mapview)
library(units)

```

```{r}
Sys.setenv(CENSUS_KEY="0f0e2bffc9d96d5405bcb932e25318a4edb32602")

acs_vars_2019_5yr <-
  listCensusMetadata(
    name = "2019/acs/acs5",
    type = "variables"
  )

```

# 6-POINT WORK

```{r}
#Import data and tidy to estimates within each education type - need to repeat for all races

census_race_categories <- 
  c(
    "White Alone",
    "Black or African American",
    "American Indian and Alaska Native Alone",
    "Asian Alone",
    "Native Hawaiian and Other Pacific Islander Alone",
    "Some Other Race Alone",
    "Two or More Races"
  )

sc_edu <- 
  1:7 %>%
  map_dfr(function(x){
   getCensus(
    name = "acs/acs5",
    vintage = 2019,
    region = "county:085", 
    regionin = "state:06",
    vars = paste0("group(C15002", LETTERS[x], ")")
   ) %>%
  select(!c(GEO_ID,state,NAME) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "name",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_5yr %>% 
      select(name, label)
  ) %>% 
  select(-name) %>% 
  separate(
    label,
    into = c(NA,NA,NA,"education"),
    sep = "!!"
  ) %>% 
  filter(!is.na(education)) %>%
  mutate(race = census_race_categories[x]) %>%
  select(-county)
})
```


```{r}
  sc_edu_total <- 
      sc_edu %>%
      group_by(race) %>%
      summarize(estimate = sum(estimate)) %>%
      mutate(education = "Total")
```


```{r}
sc_edu %>% 
  group_by(education, race) %>%
  summarize(estimate = sum(estimate)) %>%
  rbind(sc_edu_total) %>%
  ggplot() +
  geom_bar(
    aes(
      x = education %>% factor(levels = rev(c("Total",unique(sc_edu$education)))),
      y = estimate,
      fill = race %>% factor(levels = rev(unique(sc_edu$race)))
      ),
    stat = "identity",
    position = "stack"
  ) +
  labs(
    x = "Educational Attainment",
    y = "Number of Population 25 years or Older",
    title = "Santa Clara Educational Attainment by Race",
    fill = "Race of householder"
  ) +
  coord_flip() +
  theme(
    legend.position = "bottom",
    legend.direction = "vertical"
  ) +
  guides(
    fill = guide_legend(
      reverse = T)
  )
```

```{r}
sc_edu %>% 
  group_by(education, race) %>%
  summarize(estimate = sum(estimate)) %>%
  rbind(sc_edu_total) %>%
  ggplot() +
  geom_bar(
    aes(
      x = education %>% factor(levels = rev(c("Total",unique(sc_edu$education)))),
      y = estimate,
      fill = race %>% factor(levels = rev(unique(sc_edu$race)))
      ),
    stat = "identity",
    position = "fill"
  ) +
  labs(
    x = "Educational Attainment",
    y = "Proportion of Population 25 years or Older",
    title = "Santa Clara Educational Attainment by Race",
    fill = "Race of householder"
  ) +
  coord_flip() +
  theme(
    legend.position = "bottom",
    legend.direction = "vertical"
  ) +
  guides(
    fill = guide_legend(
      reverse = T)
  )
```
#6.5 POINT WORK


```{r}
census_race_categories2 <- 
  c("","","","","","","", 
    "Latinx",
    "White, not latinx"
  )

sc_edu2 <- 
  8:9 %>%
  map_dfr(function(x){
   getCensus(
    name = "acs/acs5",
    vintage = 2019,
    region = "county:085", 
    regionin = "state:06",
    vars = paste0("group(C15002", LETTERS[x], ")")
   ) %>%
  select(!c(GEO_ID,state,NAME) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "name",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_5yr %>% 
      select(name, label)
  ) %>% 
  select(-name) %>% 
  separate(
    label,
    into = c(NA,NA,NA,"education"),
    sep = "!!"
  ) %>% 
  filter(!is.na(education)) %>%
  mutate(race = census_race_categories2[x]) %>%
  select(-county)
})
```

```{r}
#get total education number
sc_edu_total2 <-
  sc_edu %>%
  group_by(education) %>%
  summarize(estimate = sum(estimate))

#total education minus sum of latinX & White, not Latinx
not_white_latin <- sc_edu2 %>%
  group_by(education) %>%
  summarize(estimate = sum(estimate)) %>%
  mutate(estimate = sc_edu_total2$estimate - not_white_latin$estimate) %>%
  mutate(race = "Not White, Not LatinX") 

#bind the two
sc_edu2 <- sc_edu2 %>%
  rbind(not_white_latin) %>%
  group_by(education, race) %>%
  summarize(estimate = sum(estimate))

#Get Total's - need to split up into latin x, white, none classifiers

          
  )

```

```{r}
#PLOT

sc_edu2 %>% 
  group_by(education, race) %>%
  summarize(estimate = sum(estimate)) %>%
  rbind(sc_edu2 %>% 
          group_by(race) %>%
          summarize(estimate = sum(estimate)) %>%
          mutate(education = "Total")) %>%
  ggplot() +
  geom_bar(
    aes(
      x = education %>% factor(levels = rev(c("Total",unique(sc_edu2$education)))),
      y = estimate,
      fill = race %>% factor(levels = rev(unique(sc_edu2$race)))
      ),
    stat = "identity",
    position = "stack"
  ) +
  labs(
    x = "Educational Attainment",
    y = "Number of Population 25 years or Older",
    title = "Santa Clara Educational Attainment by Race",
    fill = "Race of householder"
  ) +
  coord_flip() +
  theme(
    legend.position = "bottom",
    legend.direction = "vertical"
  ) +
  guides(
    fill = guide_legend(
      reverse = T)
  )
```

```{r}
sc_edu2 %>% 
  group_by(education, race) %>%
  summarize(estimate = sum(estimate)) %>%
  rbind(sc_edu2 %>% 
          group_by(race) %>%
          summarize(estimate = sum(estimate)) %>%
          mutate(education = "Total")) %>%
  ggplot() +
  geom_bar(
    aes(
      x = education %>% factor(levels = rev(c("Total",unique(sc_edu2$education)))),
      y = estimate,
      fill = race %>% factor(levels = rev(unique(sc_edu2$race)))
      ),
    stat = "identity",
    position = "fill"
  ) +
  labs(
    x = "Educational Attainment",
    y = "Number of Population 25 years or Older",
    title = "Santa Clara Educational Attainment by Race",
    fill = "Race of householder"
  ) +
  coord_flip() +
  theme(
    legend.position = "bottom",
    legend.direction = "vertical"
  ) +
  guides(
    fill = guide_legend(
      reverse = T)
  )
```

